DOCS =									\
		faq							\
		windows							\
		http/request_processing					\
		http/server_names					\
		http/configuring_https_servers				\
		debugging_log						\
		http/converting_rewrite_rules				\

FAQ =									\
		sys_errlist						\
