DOCS =									\
		faq							\
		windows							\
		syntax							\
		dirindex						\
		http/request_processing					\
		http/server_names					\
		http/configuring_https_servers				\
		debugging_log						\
		http/converting_rewrite_rules				\

FAQ =									\
		welcome_nginx_facebook					\
		sys_errlist						\

REFS =									\
		http/ngx_http_access_module				\
		http/ngx_http_addition_module				\
		http/ngx_http_auth_basic_module				\
		http/ngx_http_autoindex_module				\
		http/ngx_http_browser_module				\
		http/ngx_http_gzip_static_module			\
		http/ngx_http_index_module				\
		http/ngx_http_limit_conn_module				\
